# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SFXCoding
email: tom@sfxcode.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.




baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: sfxcode
github_username:  sfxcode

minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

author:
  name   : "Tom"
  avatar : "/assets/images/sfxcode-logo.png"
  bio    : "Like Coding and IT Technologies. Also work as Club DJ."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sfxcode"
    - label: "sapphire-core"
      icon: "fab fa-fw fa-github"
      url: https://sfxcode.github.io/sapphire-core/
    - label: "simple-mongo"
      icon: "fab fa-fw fa-github"
      url: https://sfxcode.github.io/simple-mongo/
    - label: "sbt-paradox-reveal"
      icon: "fab fa-fw fa-github"
      url: https://sfxcode.github.io/sbt-paradox-reveal/


footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sfxcode"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sfxcode"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
